apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: zt-security
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-sa
      containers:
        - name: vault
          image: hashicorp/vault:1.15
          securityContext:
            runAsUser: 100
          command: ["vault", "server", "-config=/vault/config/vault.hcl"]
          ports:
            - containerPort: 8200
          volumeMounts:
            - name: vault-config
              mountPath: /vault/config
            - name: vault-data
              mountPath: /vault/data
      volumes:
        - name: vault-config
          configMap:
            name: vault-config
        - name: vault-data
          emptyDir: {}
