apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: zt-identity
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: zt-security
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: zt-data
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: zt-apps
  labels:
    istio-injection: enabled
