apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms1-profile-aggregator-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms2-employee-details-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms3-hardware-assets-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms4-holiday-calendar-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ms5-office-locations-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db-seeder-sa
  namespace: zt-apps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: zt-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-migration-sa
  namespace: zt-data
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-sa
  namespace: zt-identity
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: zt-security
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerbos-sa
  namespace: zt-security
