apiVersion: v1
kind: Secret
metadata:
  name: auth-service-credentials
  namespace: zt-apps
type: Opaque
stringData:
  DATABASE_URL: "postgresql://auth_service_app:auth_pass@postgres.zt-data.svc.cluster.local:5432/hr_directory"
  KEYCLOAK_CLIENT_SECRET: "auth-service-client-secret-local-poc"
