apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: zt-identity
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin" # POC local password
  KEYCLOAK_CLIENT_SECRET: "auth-service-client-secret-local-poc"
